### ISSUE TITLE
[BUG] about _tkinter.TclError: couldn't open "xxxxxx\tkfilebrowser\images\file.png": no such file or directory

### ISSUE THREAD

**Issue by haobo724** [j4321/tkFileBrowser#24]
recently I wrote a simple GUI Programm which has used tkFileBrowser . It works well and I appreciate it.

But when i package this .py Script into .exe flie with pyinstaller ,the problems arise.

When i double click the .exe , the programm works well but if i click the Button "opendirs" which command is askopendirnames from tkFileBrowser . then occour error : 

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "auto.py", line 58, in seldirs
  File "tkfilebrowser\functions.py", line 101, in askopendirnames
  File "tkfilebrowser\filebrowser.py", line 210, in __init__
  File "tkinter\__init__.py", line 3545, in __init__
  File "tkinter\__init__.py", line 3501, in __init__
_tkinter.TclError: couldn't open ".\tkfilebrowser\images\file.png": no such file or directory

and dialog shows empty ,just blank

I checked the dependencies in exe folder ,there is no .\tkfilebrowser folder  in my .exe path . Then i copy the tkfilebrowser from your github site in exe folder  then everything is fine .
I'm not sure if this issue from tkfilebrowser or from pyinstaller, but if I don't use askopendirnames then the program will be  fine. Just reporting on it, maybe you know the answer.

**Comment by quentinhamard** [comment]
When you create the .exe with pyinstaller enter this command :
pyinstaller.exe --onefile --add-data C:\ProgramData\Anaconda3\Lib\site-packages\tkfilebrowser\images;tkfilebrowser\images CopieDossiersSansAudioNiCamera.py

**Comment by MightiD** [comment]
Im having the same problem and the previous comment didnt help because it said it couldnt find the path:  C:\ProgramData\Anaconda3\Lib\site-packages\tkfilebrowser\images;tkfilebrowser\images
